export const CONFIG = {
  api: 'https://my-json-server.typicode.com/SergeySalimov/FE2-project',
  dNone: 'd-none',
  active: 'active',
  elements: {
    productsPlace: document.getElementById('product-place'),
    homePage: document.getElementById('home'),
    errorPage: document.getElementById('error-page'),
    howToBuyPage: document.getElementById('how-to-buy'),
    catalogPage: document.getElementById('catalog'),
    deliveryPage: document.getElementById('delivery'),
    paymentPage: document.getElementById('payment'),
    contactPage: document.getElementById('contact'),
    navBtnCatalog: document.querySelector('.btn-nav-catalog'),
    navBtnHowToBuy: document.querySelector('.btn-nav-how-to-buy'),
    navBtnDelivery: document.querySelector('.btn-nav-delivery'),
    navBtnPayment: document.querySelector('.btn-nav-payment'),
    navBtnContact: document.querySelector('.btn-nav-contact'),
    nav2: document.getElementById('nav2'),
    nav2Home: document.getElementById('nav2-home'),
    errorBack: document.getElementById('error-to-home'),
    catBtn: document.getElementById('catalog-navigation'),
    catBtnHome: document.getElementById('btn-catalog'),
  },

};
